"""initial schema

Revision ID: fed74730d640
Revises: 
Create Date: 2026-08-07 09:52:11.908694
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import tmo.db.base  # noqa: F401 — UtcDateTime используется в определениях колонок

revision = 'fed74730d640'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('name_en', sa.String(length=120), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('attributes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_cities'))
    )
    op.create_table('market_snapshots',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('started_at', tmo.db.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('primary_collection_finished_at', tmo.db.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('recovery_finished_at', tmo.db.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('published_at', tmo.db.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('coverage_total', sa.Float(), nullable=False),
    sa.Column('coverage_rail', sa.Float(), nullable=False),
    sa.Column('coverage_air', sa.Float(), nullable=False),
    sa.Column('coverage_hotel', sa.Float(), nullable=False),
    sa.Column('quality_summary', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('publication_notes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', tmo.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_snapshots')),
    sa.UniqueConstraint('snapshot_date', 'attempt_no', name='uq_snapshot_date_attempt')
    )
    op.create_index(op.f('ix_market_snapshots_snapshot_date'), 'market_snapshots', ['snapshot_date'], unique=False)
    op.create_index('ix_market_snapshots_status_date', 'market_snapshots', ['status', 'snapshot_date'], unique=False)
    op.create_table('methodology_profiles',
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('content', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('registered_at', tmo.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('version', name=op.f('pk_methodology_profiles'))
    )
    op.create_table('sources',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('protocol', sa.String(length=16), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('attributes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_sources'))
    )
    op.create_table('calculation_runs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('snapshot_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('methodology_version', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('started_at', tmo.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('finished_at', tmo.db.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('metrics_count', sa.Integer(), nullable=False),
    sa.Column('offers_considered', sa.Integer(), nullable=False),
    sa.Column('offers_included', sa.Integer(), nullable=False),
    sa.Column('gate_results', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['methodology_version'], ['methodology_profiles.version'], name=op.f('fk_calculation_runs_methodology_version_methodology_profiles')),
    sa.ForeignKeyConstraint(['snapshot_id'], ['market_snapshots.id'], name=op.f('fk_calculation_runs_snapshot_id_market_snapshots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calculation_runs'))
    )
    op.create_index('ix_calculation_runs_snapshot_active', 'calculation_runs', ['snapshot_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_calculation_runs_snapshot_id'), 'calculation_runs', ['snapshot_id'], unique=False)
    op.create_table('collection_jobs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('snapshot_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('family', sa.String(length=32), nullable=False),
    sa.Column('job_key', sa.String(length=64), nullable=False),
    sa.Column('series_key', sa.String(length=64), nullable=False),
    sa.Column('origin_code', sa.String(length=8), nullable=True),
    sa.Column('destination_code', sa.String(length=8), nullable=True),
    sa.Column('city_code', sa.String(length=8), nullable=True),
    sa.Column('service_date', sa.Date(), nullable=True),
    sa.Column('return_date', sa.Date(), nullable=True),
    sa.Column('check_in', sa.Date(), nullable=True),
    sa.Column('check_out', sa.Date(), nullable=True),
    sa.Column('stars', sa.Integer(), nullable=True),
    sa.Column('day_offset', sa.Integer(), nullable=True),
    sa.Column('nights', sa.Integer(), nullable=True),
    sa.Column('params', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('no_market_reason', sa.String(length=32), nullable=True),
    sa.Column('is_partial', sa.Boolean(), nullable=False),
    sa.Column('offers_count', sa.Integer(), nullable=False),
    sa.Column('sources_planned', sa.Integer(), nullable=False),
    sa.Column('sources_succeeded', sa.Integer(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('first_dispatched_at', tmo.db.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('completed_at', tmo.db.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', tmo.db.base.UtcDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['market_snapshots.id'], name=op.f('fk_collection_jobs_snapshot_id_market_snapshots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collection_jobs')),
    sa.UniqueConstraint('snapshot_id', 'job_key', name='uq_collection_jobs_snapshot_job_key')
    )
    op.create_index('ix_collection_jobs_hotel', 'collection_jobs', ['family', 'city_code', 'check_in', 'stars'], unique=False)
    op.create_index('ix_collection_jobs_route', 'collection_jobs', ['family', 'origin_code', 'destination_code', 'service_date'], unique=False)
    op.create_index('ix_collection_jobs_series', 'collection_jobs', ['series_key', 'snapshot_id'], unique=False)
    op.create_index('ix_collection_jobs_snapshot_family_status', 'collection_jobs', ['snapshot_id', 'family', 'status'], unique=False)
    op.create_index(op.f('ix_collection_jobs_snapshot_id'), 'collection_jobs', ['snapshot_id'], unique=False)
    op.create_table('collection_plans',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('snapshot_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('planned', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Integer(), nullable=False),
    sa.Column('successful', sa.Integer(), nullable=False),
    sa.Column('partial', sa.Integer(), nullable=False),
    sa.Column('no_market', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('missing', sa.Integer(), nullable=False),
    sa.Column('by_family', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('plan_digest', sa.String(length=64), nullable=False),
    sa.Column('built_at', tmo.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['market_snapshots.id'], name=op.f('fk_collection_plans_snapshot_id_market_snapshots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collection_plans')),
    sa.UniqueConstraint('snapshot_id', name=op.f('uq_collection_plans_snapshot_id'))
    )
    op.create_table('snapshot_source_results',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('snapshot_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('source_code', sa.String(length=32), nullable=False),
    sa.Column('family', sa.String(length=32), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('success', sa.Integer(), nullable=False),
    sa.Column('partial', sa.Integer(), nullable=False),
    sa.Column('no_market', sa.Integer(), nullable=False),
    sa.Column('failures_by_outcome', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('offers_parsed', sa.Integer(), nullable=False),
    sa.Column('http_calls', sa.Integer(), nullable=False),
    sa.Column('p50_latency_ms', sa.Integer(), nullable=True),
    sa.Column('p95_latency_ms', sa.Integer(), nullable=True),
    sa.Column('first_fetched_at', tmo.db.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('last_fetched_at', tmo.db.base.UtcDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['market_snapshots.id'], name=op.f('fk_snapshot_source_results_snapshot_id_market_snapshots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_snapshot_source_results')),
    sa.UniqueConstraint('snapshot_id', 'source_code', 'family', name='uq_snapshot_source_family')
    )
    op.create_index(op.f('ix_snapshot_source_results_snapshot_id'), 'snapshot_source_results', ['snapshot_id'], unique=False)
    op.create_table('calculated_metrics',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('calculation_run_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('snapshot_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('collection_job_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('metric_type', sa.String(length=32), nullable=False),
    sa.Column('series_key', sa.String(length=64), nullable=False),
    sa.Column('origin_code', sa.String(length=8), nullable=True),
    sa.Column('destination_code', sa.String(length=8), nullable=True),
    sa.Column('city_code', sa.String(length=8), nullable=True),
    sa.Column('service_date', sa.Date(), nullable=True),
    sa.Column('return_date', sa.Date(), nullable=True),
    sa.Column('check_in', sa.Date(), nullable=True),
    sa.Column('check_out', sa.Date(), nullable=True),
    sa.Column('stars', sa.Integer(), nullable=True),
    sa.Column('day_offset', sa.Integer(), nullable=True),
    sa.Column('nights', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('median_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('min_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('max_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('p25_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('p75_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('offers_count', sa.Integer(), nullable=False),
    sa.Column('offers_excluded', sa.Integer(), nullable=False),
    sa.Column('sources_count', sa.Integer(), nullable=False),
    sa.Column('source_coverage', sa.Float(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('confidence_level', sa.String(length=32), nullable=False),
    sa.Column('is_partial', sa.Boolean(), nullable=False),
    sa.Column('is_no_market', sa.Boolean(), nullable=False),
    sa.Column('no_market_reason', sa.String(length=32), nullable=True),
    sa.Column('warning_codes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('per_source', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('fetched_at', tmo.db.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('computed_at', tmo.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['calculation_run_id'], ['calculation_runs.id'], name=op.f('fk_calculated_metrics_calculation_run_id_calculation_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['collection_job_id'], ['collection_jobs.id'], name=op.f('fk_calculated_metrics_collection_job_id_collection_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['market_snapshots.id'], name=op.f('fk_calculated_metrics_snapshot_id_market_snapshots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calculated_metrics')),
    sa.UniqueConstraint('calculation_run_id', 'collection_job_id', 'metric_type', name='uq_metric_run_job_type')
    )
    op.create_index(op.f('ix_calculated_metrics_calculation_run_id'), 'calculated_metrics', ['calculation_run_id'], unique=False)
    op.create_index(op.f('ix_calculated_metrics_collection_job_id'), 'calculated_metrics', ['collection_job_id'], unique=False)
    op.create_index('ix_metrics_hotel', 'calculated_metrics', ['calculation_run_id', 'metric_type', 'city_code', 'check_in', 'stars'], unique=False)
    op.create_index('ix_metrics_route', 'calculated_metrics', ['calculation_run_id', 'metric_type', 'origin_code', 'destination_code', 'service_date'], unique=False)
    op.create_index('ix_metrics_series', 'calculated_metrics', ['series_key', 'snapshot_id'], unique=False)
    op.create_index('ix_metrics_snapshot_type', 'calculated_metrics', ['snapshot_id', 'metric_type'], unique=False)
    op.create_table('source_attempts',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('snapshot_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('collection_job_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('source_code', sa.String(length=32), nullable=False),
    sa.Column('execution_scope', sa.String(length=24), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('no_market_reason', sa.String(length=32), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('requested_at', tmo.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('fetched_at', tmo.db.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('http_calls', sa.Integer(), nullable=False),
    sa.Column('offers_parsed', sa.Integer(), nullable=False),
    sa.Column('is_partial', sa.Boolean(), nullable=False),
    sa.Column('partial_reason', sa.String(length=64), nullable=True),
    sa.Column('pages_read', sa.Integer(), nullable=False),
    sa.Column('total_matched', sa.Integer(), nullable=True),
    sa.Column('connector_version', sa.String(length=32), nullable=False),
    sa.Column('source_tool_version', sa.String(length=64), nullable=True),
    sa.Column('diagnostics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['collection_job_id'], ['collection_jobs.id'], name=op.f('fk_source_attempts_collection_job_id_collection_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['market_snapshots.id'], name=op.f('fk_source_attempts_snapshot_id_market_snapshots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_attempts')),
    sa.UniqueConstraint('idempotency_key', name='uq_source_attempts_idempotency_key')
    )
    op.create_index(op.f('ix_source_attempts_collection_job_id'), 'source_attempts', ['collection_job_id'], unique=False)
    op.create_index('ix_source_attempts_fetched_at', 'source_attempts', ['fetched_at'], unique=False)
    op.create_index('ix_source_attempts_job_source', 'source_attempts', ['collection_job_id', 'source_code'], unique=False)
    op.create_index(op.f('ix_source_attempts_snapshot_id'), 'source_attempts', ['snapshot_id'], unique=False)
    op.create_index('ix_source_attempts_snapshot_outcome', 'source_attempts', ['snapshot_id', 'source_code', 'outcome'], unique=False)
    op.create_table('trip_cost_mart',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('calculation_run_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('snapshot_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('origin_code', sa.String(length=8), nullable=False),
    sa.Column('destination_code', sa.String(length=8), nullable=False),
    sa.Column('departure_date', sa.Date(), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=False),
    sa.Column('transport_mode', sa.String(length=8), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('nights', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('transport_median', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('transport_min', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('accommodation_median', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('accommodation_min', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('total_median', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('total_min', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('transport_metric_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('accommodation_metric_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('offers_count', sa.Integer(), nullable=False),
    sa.Column('sources_count', sa.Integer(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('confidence_level', sa.String(length=32), nullable=False),
    sa.Column('is_partial', sa.Boolean(), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('warning_codes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('missing_components', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['calculation_run_id'], ['calculation_runs.id'], name=op.f('fk_trip_cost_mart_calculation_run_id_calculation_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['market_snapshots.id'], name=op.f('fk_trip_cost_mart_snapshot_id_market_snapshots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trip_cost_mart')),
    sa.UniqueConstraint('calculation_run_id', 'origin_code', 'destination_code', 'departure_date', 'return_date', 'transport_mode', 'stars', name='uq_trip_cost_row')
    )
    op.create_index('ix_trip_cost_lookup', 'trip_cost_mart', ['calculation_run_id', 'origin_code', 'departure_date', 'return_date', 'transport_mode', 'stars'], unique=False)
    op.create_index(op.f('ix_trip_cost_mart_calculation_run_id'), 'trip_cost_mart', ['calculation_run_id'], unique=False)
    op.create_table('raw_responses',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('snapshot_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('source_attempt_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('source_code', sa.String(length=32), nullable=False),
    sa.Column('endpoint', sa.String(length=512), nullable=False),
    sa.Column('request_params', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('requested_at', tmo.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('fetched_at', tmo.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(length=64), nullable=False),
    sa.Column('storage_ref', sa.String(length=512), nullable=False),
    sa.Column('payload_bytes', sa.Integer(), nullable=False),
    sa.Column('payload_sha256', sa.String(length=64), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('pagination', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('is_partial', sa.Boolean(), nullable=False),
    sa.Column('error_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['market_snapshots.id'], name=op.f('fk_raw_responses_snapshot_id_market_snapshots'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_attempt_id'], ['source_attempts.id'], name=op.f('fk_raw_responses_source_attempt_id_source_attempts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_raw_responses'))
    )
    op.create_index('ix_raw_responses_fetched_at', 'raw_responses', ['fetched_at'], unique=False)
    op.create_index('ix_raw_responses_snapshot_source', 'raw_responses', ['snapshot_id', 'source_code'], unique=False)
    op.create_index(op.f('ix_raw_responses_source_attempt_id'), 'raw_responses', ['source_attempt_id'], unique=False)
    op.create_table('offers',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('snapshot_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('collection_job_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('source_attempt_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('raw_response_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('source_code', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('schema_version', sa.String(length=16), nullable=False),
    sa.Column('fetched_at', tmo.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('source_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('price_basis', sa.String(length=32), nullable=False),
    sa.Column('origin_code', sa.String(length=8), nullable=True),
    sa.Column('destination_code', sa.String(length=8), nullable=True),
    sa.Column('city_code', sa.String(length=8), nullable=True),
    sa.Column('departure_at', tmo.db.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('arrival_at', tmo.db.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('return_departure_at', tmo.db.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('return_arrival_at', tmo.db.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('check_in', sa.Date(), nullable=True),
    sa.Column('check_out', sa.Date(), nullable=True),
    sa.Column('nights', sa.Integer(), nullable=True),
    sa.Column('transport_attributes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('property_attributes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('source_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('equivalence_key', sa.String(length=64), nullable=False),
    sa.Column('deeplink', sa.String(length=1024), nullable=True),
    sa.Column('validation_flags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.CheckConstraint('price > 0', name=op.f('ck_offers_offer_price_positive')),
    sa.ForeignKeyConstraint(['collection_job_id'], ['collection_jobs.id'], name=op.f('fk_offers_collection_job_id_collection_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raw_response_id'], ['raw_responses.id'], name=op.f('fk_offers_raw_response_id_raw_responses'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['market_snapshots.id'], name=op.f('fk_offers_snapshot_id_market_snapshots'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_attempt_id'], ['source_attempts.id'], name=op.f('fk_offers_source_attempt_id_source_attempts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_offers'))
    )
    op.create_index('ix_offers_equivalence', 'offers', ['collection_job_id', 'source_code', 'equivalence_key'], unique=False)
    op.create_index('ix_offers_job', 'offers', ['collection_job_id'], unique=False)
    op.create_index('ix_offers_raw_response_id', 'offers', ['raw_response_id'], unique=False)
    op.create_index('ix_offers_snapshot_kind', 'offers', ['snapshot_id', 'kind'], unique=False)
    op.create_index(op.f('ix_offers_source_attempt_id'), 'offers', ['source_attempt_id'], unique=False)
    op.create_table('metric_offer_links',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('metric_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('offer_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('is_included', sa.Boolean(), nullable=False),
    sa.Column('exclusion_reason', sa.String(length=32), nullable=True),
    sa.Column('exclusion_detail', sa.String(length=255), nullable=True),
    sa.Column('contributed_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['metric_id'], ['calculated_metrics.id'], name=op.f('fk_metric_offer_links_metric_id_calculated_metrics'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], name=op.f('fk_metric_offer_links_offer_id_offers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metric_offer_links')),
    sa.UniqueConstraint('metric_id', 'offer_id', name='uq_metric_offer')
    )
    op.create_index('ix_metric_offer_links_metric_included', 'metric_offer_links', ['metric_id', 'is_included'], unique=False)
    op.create_index('ix_metric_offer_links_offer', 'metric_offer_links', ['offer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_metric_offer_links_offer', table_name='metric_offer_links')
    op.drop_index('ix_metric_offer_links_metric_included', table_name='metric_offer_links')
    op.drop_table('metric_offer_links')
    op.drop_index(op.f('ix_offers_source_attempt_id'), table_name='offers')
    op.drop_index('ix_offers_snapshot_kind', table_name='offers')
    op.drop_index('ix_offers_raw_response_id', table_name='offers')
    op.drop_index('ix_offers_job', table_name='offers')
    op.drop_index('ix_offers_equivalence', table_name='offers')
    op.drop_table('offers')
    op.drop_index(op.f('ix_raw_responses_source_attempt_id'), table_name='raw_responses')
    op.drop_index('ix_raw_responses_snapshot_source', table_name='raw_responses')
    op.drop_index('ix_raw_responses_fetched_at', table_name='raw_responses')
    op.drop_table('raw_responses')
    op.drop_index(op.f('ix_trip_cost_mart_calculation_run_id'), table_name='trip_cost_mart')
    op.drop_index('ix_trip_cost_lookup', table_name='trip_cost_mart')
    op.drop_table('trip_cost_mart')
    op.drop_index('ix_source_attempts_snapshot_outcome', table_name='source_attempts')
    op.drop_index(op.f('ix_source_attempts_snapshot_id'), table_name='source_attempts')
    op.drop_index('ix_source_attempts_job_source', table_name='source_attempts')
    op.drop_index('ix_source_attempts_fetched_at', table_name='source_attempts')
    op.drop_index(op.f('ix_source_attempts_collection_job_id'), table_name='source_attempts')
    op.drop_table('source_attempts')
    op.drop_index('ix_metrics_snapshot_type', table_name='calculated_metrics')
    op.drop_index('ix_metrics_series', table_name='calculated_metrics')
    op.drop_index('ix_metrics_route', table_name='calculated_metrics')
    op.drop_index('ix_metrics_hotel', table_name='calculated_metrics')
    op.drop_index(op.f('ix_calculated_metrics_collection_job_id'), table_name='calculated_metrics')
    op.drop_index(op.f('ix_calculated_metrics_calculation_run_id'), table_name='calculated_metrics')
    op.drop_table('calculated_metrics')
    op.drop_index(op.f('ix_snapshot_source_results_snapshot_id'), table_name='snapshot_source_results')
    op.drop_table('snapshot_source_results')
    op.drop_table('collection_plans')
    op.drop_index(op.f('ix_collection_jobs_snapshot_id'), table_name='collection_jobs')
    op.drop_index('ix_collection_jobs_snapshot_family_status', table_name='collection_jobs')
    op.drop_index('ix_collection_jobs_series', table_name='collection_jobs')
    op.drop_index('ix_collection_jobs_route', table_name='collection_jobs')
    op.drop_index('ix_collection_jobs_hotel', table_name='collection_jobs')
    op.drop_table('collection_jobs')
    op.drop_index(op.f('ix_calculation_runs_snapshot_id'), table_name='calculation_runs')
    op.drop_index('ix_calculation_runs_snapshot_active', table_name='calculation_runs')
    op.drop_table('calculation_runs')
    op.drop_table('sources')
    op.drop_table('methodology_profiles')
    op.drop_index('ix_market_snapshots_status_date', table_name='market_snapshots')
    op.drop_index(op.f('ix_market_snapshots_snapshot_date'), table_name='market_snapshots')
    op.drop_table('market_snapshots')
    op.drop_table('cities')
    # ### end Alembic commands ###
